chan(install.sh): remove `-qq` from most `apt` invocations
pacstall/pacstall pull request #1030
Opened 2024-01-27 08:36 UTC by vigress8

Downloading a potentially large amount of data quietly makes the install look like it hangs. There's no good reason to hide this information from the user.

2024-01-27 21:20 UTC, D-Brox submitted a review, later dismissed

2024-01-27 23:56 UTC, Elsie19 commented
We have it quiet so that the CI logs don't balloon in size.

2024-01-28 02:02 UTC, D-Brox commented
> We have it quiet so that the CI logs don't balloon in size.

@Elsie19 then only run quiet in the CI, duh

2024-01-28 02:10 UTC, Elsie19 commented
> > We have it quiet so that the CI logs don't balloon in size.
> 
> @Elsie19 then only run quiet in the CI, duh

![](https://media1.tenor.com/m/uBcbvnuP3K0AAAAd/lil-yachty-drake.gif)

2024-01-30 03:50 UTC, Elsie19 requested changes
Make it quiet if `GITHUB_ACTIONS` variable is set.

2024-03-30 07:22 UTC, oklopfer approved these changes
works merging

2024-03-30 07:23 UTC, oklopfer commented
just kidding I always triple check with @Elsie19

2024-03-30 13:50 UTC, Elsie19 approved these changes

2024-03-30 13:51 UTC, merged