feat(CI): turn docker images into locally produced matrix
pacstall/pacstall pull request #1041
Opened 2024-02-22 08:14 UTC by oklopfer

## Purpose

need both multi-arch (amd64+arm64) and multi-distro (ubuntu+debian) images. 

## Approach

see progress

## Progress

- [x] fork my https://github.com/rhino-linux/docker program into https://github.com/pacstall/docker for storage of the dockerfile construction script
- [x] create a super dynamic workflow file that can run independent of the docker repository, as it can just curl in the above mentioned script
- [x] have it publish on pushes to master + develop, and tag creation
- [ ] figure out how to name master + develop docker tags `${branch}-${git_hash}` instead of `${branch}-${YYYYMMDD}`

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2024-02-22 14:57 UTC, oklopfer commented
Idk it's acting weird rn

2024-02-22 16:38 UTC, oklopfer commented
https://github.com/pacstall/docker/actions/runs/8007690263

idk its working here for some reason

2024-02-24 05:51 UTC, Elsie19 requested changes

2024-02-24 05:51 UTC, Elsie19 commented on .github/workflows/publish-docker.yml
> +          echo "DOCK_LABEL=${vertag}"  >> $GITHUB_ENV
```suggestion
          echo "DOCK_LABEL=${vertag}" >> $GITHUB_ENV
```

2024-02-24 05:59 UTC, Elsie19 approved these changes
LGTM 🚀 (I suppose)

2024-02-24 06:00 UTC, merged