fix(bwrap): fetch cargo crates
pacstall/pacstall pull request #1101
Opened 2024-05-06 19:40 UTC by D-Brox

## Purpose

Since we tmpfs `/run` with bwrap, cargo is unable to resolve index.crates.io

## Approach

Fetch crate dependencies outside bwrap before building

## Progress

Done and tested with multiple packages, with and without cargo

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2024-05-06 21:13 UTC, Elsie19 requested changes

2024-05-06 21:13 UTC, Elsie19 commented on misc/scripts/fetch-sources.sh
> +            CARGO_HOME="${srcdir}/.cargo" cargo fetch --manifest-path="$crate" --target "$(cargo -vV | grep "host" | cut -d' ' -f2)"
```suggestion
            CARGO_HOME="${srcdir}/.cargo" cargo fetch --manifest-path="$crate" --target "$(rustc -vV | sed -n 's|host: ||p')"
```

2024-05-07 15:14 UTC, Elsie19 requested changes

2024-05-07 15:14 UTC, Elsie19 commented on misc/scripts/fetch-sources.sh
> +    local cargo_toml=($(find "${srcdir}" -name Cargo.toml))
Use mapfile.

2024-05-07 22:01 UTC, oklopfer approved these changes

2024-05-07 22:02 UTC, oklopfer requested changes

2024-05-07 22:02 UTC, oklopfer commented on misc/scripts/bwrap.sh
> +        dns_resolve="--ro-bind /run/systemd/resolve /run/systemd/resolve"
this will almost assuredly cause issues in docker containers.

2024-05-07 22:26 UTC, oklopfer approved these changes

2024-05-07 22:26 UTC, merged