fix({fetch-sources,package}.sh): install builddeps as a dummy
pacstall/pacstall pull request #1132
Opened 2024-05-30 02:09 UTC by oklopfer

## Purpose

unneeded builddeps can be marked for auto removal 

## Approach

build a dummy

## Progress

- [x] do it
- [x] test it
- [ ] test it extensively

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2024-05-30 02:28 UTC, oklopfer commented
```bash
Unpacking rhino-pkg (0.1.2-pacstall1~gita9bfab5b) over (0.1.2-pacstall1~gita9bfab5b) ...
Setting up rhino-pkg (0.1.2-pacstall1~gita9bfab5b) ...
sh: 0: getcwd() failed: No such file or directory
[+] INFO: Performing post install operations
	[>] Storing pacscript
	[>] Cleaning up
[+] INFO: Done installing rhino-pkg-git
```
this is getting thrown at the purge, though its all working correctly...

2024-05-30 02:33 UTC, oklopfer commented
```bash
Unpacking rhino-pkg-git-dummy-builddeps (0.1.2-pacstall1~gita9bfab5b) ...
Setting up libjsoncpp25:arm64 (1.9.5-6build1) ...
Setting up librhash0:arm64 (1.4.3-3build1) ...
Setting up cmake-data (3.29.3-1build1) ...
Setting up libarchive13t64:arm64 (3.7.2-2) ...
Setting up cmake (3.29.3-1build1) ...
Setting up rhino-pkg-git-dummy-builddeps (0.1.2-pacstall1~gita9bfab5b) ...
Processing triggers for libc-bin (2.39-0ubuntu8.1) ...
[+] INFO: Retrieving packages
[+] INFO: Cloning rhino-pkg from HEAD
	[>] Checking integrity of a9bfab5b
[+] INFO: Running functions
	[>] Running package
for i in po/*.po; do lang="$(basename "$i" .po)" && mkdir -p /usr/src/pacstall/rhino-pkg-git/usr/share/locale/"$lang"/LC_MESSAGES/ && msgfmt -o /usr/src/pacstall/rhino-pkg-git/usr/share/locale/"$lang"/LC_MESSAGES/rhino-pkg.mo po/"$lang".po ; done
install -Dm755 rhino-pkg -t /usr/src/pacstall/rhino-pkg-git/usr/bin/
[+] INFO: Packaging rhino-pkg-git as rhino-pkg
	[>] Packing control.tar
	[>] Packing data.tar
	[>] Compressing
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'rhino-pkg' instead of '/usr/src/pacstall/rhino-pkg-git.deb'
The following packages were automatically installed and are no longer required:
  cmake cmake-data libarchive13t64 libjsoncpp25 librhash0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/14.5 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /usr/src/pacstall/rhino-pkg-git.deb rhino-pkg all 0.1.2-pacstall1~gita9bfab5b [14.5 kB]
(Reading database ... 27271 files and directories currently installed.)
Preparing to unpack .../src/pacstall/rhino-pkg-git.deb ...
Unpacking rhino-pkg (0.1.2-pacstall1~gita9bfab5b) over (0.1.2-pacstall1~gita9bfab5b) ...
Setting up rhino-pkg (0.1.2-pacstall1~gita9bfab5b) ...
[+] INFO: Performing post install operations
	[>] Storing pacscript
	[>] Cleaning up
[+] INFO: Done installing rhino-pkg-git
rhino@docker-desktop:~$ 
```
fixed

2024-05-30 20:18 UTC, Elsie19 requested changes

2024-05-30 20:18 UTC, Elsie19 commented on misc/scripts/fetch-sources.sh
> +        ) || {
shouldn't we `cd` in here?

2024-05-31 00:20 UTC, oklopfer commented on misc/scripts/fetch-sources.sh
> +        ) || {
why would we need to cd?

2024-05-31 02:21 UTC, oklopfer commented on misc/scripts/fetch-sources.sh
> +            unset pre_{upgrade,install,remove} post_{upgrade,install,remove} priority provides conflicts replaces breaks gives
this will need enhances, recommends, and custom_fields unset as well with #1134

2024-06-04 20:59 UTC, Elsie19 approved these changes

2024-06-04 21:00 UTC, merged