feat(srcinfo.sh): parse remote .SRCINFO data over bash scripts
pacstall/pacstall pull request #1136
Opened 2024-06-02 04:41 UTC by oklopfer

## Purpose

it is safer and more declarative this way

## Approach

see progress

## Progress

- [x] download SRCINFOs
- [x] create a parser
- [ ] use that parsing

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2024-06-03 15:50 UTC, vigress8 requested changes

2024-06-03 15:50 UTC, vigress8 commented on misc/scripts/srcinfo.sh
> +    shopt -s extglob
```suggestion
    local already_on=0
    if shopt -q extglob; then
        already_on=1
    else
        shopt -s extglob
    fi
```

2024-06-03 15:50 UTC, vigress8 commented on misc/scripts/srcinfo.sh
> +}
```suggestion
    ((already_on)) || shopt -u extglob
}
```

2024-06-03 15:50 UTC, vigress8 commented on misc/scripts/srcinfo.sh
> +        if [[ ${loop} == *"pkgname" || ${loop} == *"pkgbase" ]]; then
```suggestion
        if [[ ${loop} == *@(pkgname|pkgbase) ]]; then
```

2024-06-04 19:34 UTC, Elsie19 approved these changes

2024-06-04 19:36 UTC, merged