fix(*): quit using tabs
pacstall/pacstall pull request #1144
Opened 2024-06-08 18:19 UTC by vigress8

2024-06-08 23:27 UTC, oklopfer submitted a review, later dismissed

2024-06-09 12:20 UTC, Elsie19 approved these changes

2024-06-09 17:11 UTC, oklopfer requested changes

2024-06-09 17:11 UTC, oklopfer commented on install.sh
> +# vim:set ft=sh ts=4 sw=4 et:
this should be added/altered on the bottom of srcinfo.sh as well

2024-06-12 20:01 UTC, oklopfer approved these changes

2024-06-12 20:08 UTC, Elsie19 approved these changes

2024-06-12 20:20 UTC, merged