fix(apt): use proper apt config locations
pacstall/pacstall pull request #1230
Opened 2024-08-31 03:11 UTC by Elsie19

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2024-08-31 12:51 UTC, D-Brox requested changes

2024-08-31 12:51 UTC, D-Brox commented on install.sh
> +if [[ -z "$(find -H "${Cache}/${List}" -maxdepth 0 -mtime -7)" ]]; then
```suggestion
if [[ -z "$(find -H "/${Cache}/${List}" -maxdepth 0 -mtime -7)" ]]; then
```

2024-08-31 12:51 UTC, D-Brox commented on pacstall
> +[[ -z "$(find -H "${Cache}/${List}" -maxdepth 0 -mtime -7)" ]] && sudo apt-get update -qq --allow-releaseinfo-change
```suggestion
[[ -z "$(find -H "/${Cache}/${List}" -maxdepth 0 -mtime -7)" ]] && sudo apt-get update -qq --allow-releaseinfo-change
```

2024-08-31 18:31 UTC, oklopfer commented on install.sh
> +if [[ -z "$(find -H "${Cache}/${List}" -maxdepth 0 -mtime -7)" ]]; then
I dont like the evals
```suggestion
Cache="$(apt-config shell Cache Dir::Cache | cut -d"'" -f2)"
List="$(apt-config shell List Dir::State::Lists | cut -d"'" -f2)"
if [[ -z "$(find -H "/${Cache}/${List}" -maxdepth 0 -mtime -7)" ]]; then
```

2024-08-31 18:34 UTC, oklopfer commented on pacstall
> +[[ -z "$(find -H "${Cache}/${List}" -maxdepth 0 -mtime -7)" ]] && sudo apt-get update -qq --allow-releaseinfo-change
```suggestion
Cache="$(apt-config shell Cache Dir::Cache | cut -d"'" -f2)"
List="$(apt-config shell List Dir::State::Lists | cut -d"'" -f2)"
[[ -z "$(find -H "/${Cache}/${List}" -maxdepth 0 -mtime -7)" ]] && sudo apt-get update -qq --allow-releaseinfo-change
```

2024-08-31 18:47 UTC, Elsie19 commented
The evals are safe, `apt-config shell` is literally made for evaling.

-------- Original Message --------
On 8/31/24 14:32, oklopfer  wrote:

> @oklopfer commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [install.sh](https://github.com/pacstall/pacstall/pull/1230#discussion_r1739901796):
>
>> +eval "$(apt-config shell Cache Dir::Cache)"
> +eval "$(apt-config shell List Dir::State::Lists)"
> +if [[ -z "$(find -H "${Cache}/${List}" -maxdepth 0 -mtime -7)" ]]; then
>
> I dont like the evals
>
> ⬇️ Suggested change
>
> -eval "$(apt-config shell Cache Dir::Cache)"
> -eval "$(apt-config shell List Dir::State::Lists)"
> -if [[ -z "$(find -H "${Cache}/${List}" -maxdepth 0 -mtime -7)" ]]; then
> +Cache="$(apt-config shell Cache Dir::Cache | cut -d"'" -f2)"
> +List="$(apt-config shell List Dir::State::Lists | cut -d"'" -f2)"
> +if [[ -z "$(find -H "/${Cache}/${List}" -maxdepth 0 -mtime -7)" ]]; then
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/pacstall/pacstall/pull/1230#pullrequestreview-2274122805), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AOAFN45JM7JUIJVBNE5HYADZUID3JAVCNFSM6AAAAABNNO3F6GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENZUGEZDEOBQGU).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-31 19:20 UTC, D-Brox commented
@Elsie19 it still needs the "/" tho, since it evals to `var/apt/lists` on normal circumstances

2024-09-01 20:22 UTC, Elsie19 commented on pacstall
> +[[ -z "$(find -H "${Cache}/${List}" -maxdepth 0 -mtime -7)" ]] && sudo apt-get update -qq --allow-releaseinfo-change
No.

2024-09-04 03:50 UTC, oklopfer approved these changes

2024-09-04 03:51 UTC, merged

2024-09-04 07:43 UTC, oklopfer commented
turns out this was a regression