Add develop flag with -Ud
pacstall/pacstall pull request #15
Opened 2021-05-25 18:08 UTC by Henryws

2021-05-25 20:50 UTC, Henryws commented
Don't merge yet

2021-05-26 10:48 UTC, wizard-28 requested changes
Also fix the CodeFactor issue

2021-05-26 10:52 UTC, Henryws commented
Codefactor failed b/c it thinks that quoting something unquotes it which is what I want to do so it's good to go

2021-05-26 10:52 UTC, Henryws commented on pacstall
> +          BRANCH=master
done

2021-05-26 10:53 UTC, wizard-28 approved these changes
Okay then good to go!

2021-05-26 10:53 UTC, merged

2021-05-26 10:53 UTC, wizard-28 commented
Why is the branch restored?

2021-05-26 10:53 UTC, Henryws commented
Oops