Add postrm in dummy deb
pacstall/pacstall pull request #175
Opened 2021-08-03 14:38 UTC by rain1598

# Purpose

Pacstall dummy packages currently cannot be removed with apt

# Approach

Adds a postrm file that calls pacstall

2021-08-03 16:03 UTC, Henryws commented
```bash
[+] INFO: Creating dummy package
dpkg-deb: error: parsing file '/tmp/pacstall/bat-pacstall/DEBIAN/control' near line 8 package 'bat-pacstall':
 'Conflicts' field, syntax error after reference to package 'bat'
[!] ERROR: Couldn't create dummy package
[!] ERROR: Failed to install bat
➜  ~
```

2021-08-03 19:34 UTC, Henryws commented
```bash
[+] INFO: Creating dummy package
dpkg-deb: error: maintainer script 'postrm' has bad permissions 644 (must be >=0555 and <=0775)
[!] ERROR: Couldn't create dummy package
[!] ERROR: Failed to install clib
```

2021-08-03 19:41 UTC, D-Brox approved these changes

2021-08-03 19:42 UTC, D-Brox requested changes

2021-08-03 19:42 UTC, D-Brox commented on misc/scripts/install-local.sh
>  	if [[ -v replace ]]; then
`if [[ -n $replace ]]` should probably fix the first issue TB pointed out

2021-08-03 19:59 UTC, Henryws commented
new bug
```bash
[+] INFO: Creating dummy package
[+] INFO: clib has optional dependencies that can enhance its functionalities
Optional dependencies:

Do you want to install them [Y/n]
```

2021-08-04 00:35 UTC, Henryws commented
```bash
[+] INFO: Creating dummy package
/var/lib/dpkg/info/clib-pacstall.postrm: 1: [[: not found
[+] INFO: Installing dependencies
/var/lib/dpkg/info/clib-pacstall.postrm: 1: [[: not found
[+] INFO: Retrieving packages
Initializing download: https://github.com/clibs/clib/archive/refs/tags/2.7.0.tar.gz
File size: unavailable
Opening output file 2.7.0.tar.gz
Server unsupported, starting from scratch with one connection.
Starting download

Connection 0 finished

Downloaded 171.974 Kilobyte(s) in 0 second(s). (423.74 KB/s)
[+] INFO: Running prepare in fakeroot. Do not enter password if prompted
[+] INFO: Running build in fakeroot. Do not enter password if prompted
make: *** No targets specified and no makefile found.  Stop.
[+] INFO: Installing
make: *** No rule to make target 'install'.  Stop.
install: cannot stat 'LICENSE': No such file or directory
[+] INFO: Symlinking files
[+] INFO: Storing pacscript
[+] INFO: Cleaning up
```

2021-08-04 02:35 UTC, D-Brox approved these changes

2021-08-04 03:47 UTC, merged

2021-08-04 03:53 UTC, D-Brox commented
I forgot to test `-git`