Feat: Unset variables in install-local.sh cleanup
pacstall/pacstall pull request #192
Opened 2021-08-15 11:22 UTC by echometerain

# Purpose

When installing multiple programs at once, variables left over may affect later installs

# Approach

It unsets the affected variables in cleanup

2021-08-16 15:34 UTC, Henryws commented
I think the reason why it's failing is because of `set -e`. What you should do is a `for i` loop that checks if one of the possible variables exists, then unset them

2021-08-16 17:47 UTC, D-Brox requested changes

2021-08-16 17:47 UTC, D-Brox commented on misc/scripts/install-local.sh
> +	unset optinstall
You can unset all in the same line

2021-08-17 12:45 UTC, D-Brox approved these changes

2021-08-18 01:46 UTC, merged