Ref/search and download
pacstall/pacstall pull request #271
Opened 2021-10-01 18:26 UTC by D-Brox

## Purpose

Add, fix and rework the messages for searching and downloading pacscripts

## Approach

Add downloading message on the main script and replace `repo pacstall` with `official repo`. Fix the `if` statement in search related to this. Change the repo names from `user` to `user/repo` when searching.

2021-10-01 18:38 UTC, Henryws approved these changes

2021-10-02 05:44 UTC, wizard-28 requested changes

2021-10-02 05:44 UTC, wizard-28 commented on pacstall
> +				fancy_message info "Downloading $GREEN${PACKAGE}.pacscript$NC from $CYAN$URLNAME$NC"
```suggestion

```

Well, it looks too verbose to me now... Let's remove it

2021-10-02 05:44 UTC, wizard-28 commented on pacstall
> +				fancy_message info "Downloading $GREEN${PACKAGE}.pacscript$NC from $CYAN$URLNAME$NC"
```suggestion

```

Well, it looks too verbose to me now... Let's remove it

2021-10-02 14:25 UTC, wizard-28 approved these changes

2021-10-02 14:25 UTC, merged