feat(completions,install): Add missing `keep` features
pacstall/pacstall pull request #330
Opened 2021-10-27 13:14 UTC by echometerain

## Purpose

This PR attempts to resolve issues laid out in https://github.com/pacstall/pacstall/commit/c08194f78e01297a11f71b4a4cd6028642a98f46#commitcomment-58773737

## Approach

Moves old builds to `/tmp/pacstall-keep/$name` and add completions

## Progress

- [x] Add -K
- [x] Add completions
- [x] Move old builds to `/tmp/pacstall-keep/$name`
- [x] Fix completions
- [x] Add splitter cases

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2021-11-04 18:27 UTC, Henryws approved these changes

2021-11-09 05:28 UTC, wizard-28 approved these changes

2021-11-10 13:23 UTC, D-Brox requested changes
Add `-K` to the arg splitter cases

It's on main script, line 228, I think

2021-11-20 07:34 UTC, wizard-28 commented
@D-Brox review pending...

2021-11-20 13:29 UTC, D-Brox requested changes
Add fancy_message on `-K`, line 553, just like in line 275 for `-P`

2021-11-20 17:46 UTC, D-Brox approved these changes

2021-11-20 18:35 UTC, merged