ref(pacstall): Convert `pacstall` to Python
pacstall/pacstall pull request #343
Opened 2021-11-10 17:22 UTC by wizard-28

## Approach

Converts `pacstall` to Python

## Progress

- [x] Halt if running as root
- [x] Update if lists older than 1 week
- [x] Write argument parser
- [ ] Write locking mechanism
- [ ] Write command launcher

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2021-11-20 07:27 UTC, wizard-28 commented
Progress stalled due to dependence on #359

2021-12-23 22:57 UTC, Henryws requested changes

2021-12-23 22:57 UTC, Henryws commented on pacstall/parser.py
> +        version=f"{Foreground.BIBLUE}Pacstall {Foreground.BIWHITE}2.0 {Foreground.BIYELLOW}Kournikova",
```suggestion
        version=f"{Foreground.BIBLUE}Pacstall {Foreground.BIWHITE}2.0.0 {Foreground.BIYELLOW}Kournikova",
```

2021-12-26 20:52 UTC, Henryws approved these changes

2021-12-27 13:58 UTC, Henryws requested changes

2021-12-27 13:58 UTC, Henryws commented on LICENSE_BOILERPLATE
> +You should have received a copy of the GNU General Public License
```suggestion
You should have received a copy of the GNU General Public License
along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
```

2021-12-27 13:58 UTC, Henryws commented on pacstall/__main__.py
> +# You should have received a copy of the GNU General Public License
```suggestion
# You should have received a copy of the GNU General Public License
# along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
```

2021-12-27 13:58 UTC, Henryws commented on pacstall/api/__init__.py
> +# You should have received a copy of the GNU General Public License
```suggestion
# You should have received a copy of the GNU General Public License
# along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
```

2021-12-27 13:58 UTC, Henryws commented on pacstall/cmds/__init__.py
> +# You should have received a copy of the GNU General Public License
```suggestion
# You should have received a copy of the GNU General Public License
# along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
```

2021-12-27 13:58 UTC, Henryws commented on pacstall/parser.py
> +# You should have received a copy of the GNU General Public License
```suggestion
# You should have received a copy of the GNU General Public License
# along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
```

2021-12-28 16:12 UTC, Henryws requested changes

2021-12-28 16:12 UTC, Henryws commented on pacstall/__init__.py
> +# You should have received a copy of the GNU General Public License
```suggestion
# You should have received a copy of the GNU General Public License
# along with Pacstall. If not, see <https://www.gnu.org/licenses/>.
```

2021-12-29 14:58 UTC, D-Brox commented on pacstall/__main__.py
> +        message.fancy("error", "Pacstall cannot be run as root")
Should we be able to bypass this with the config file? Since a sys admin may want to run pacstall

2021-12-29 15:01 UTC, D-Brox commented on pacstall/completion/bash
>  				COMPREPLY=( $( compgen -W "-I -Il -R -Up" -- "$cur" ) )
We'll have to change completions later, since we are deprecating stuff

2021-12-29 17:07 UTC, D-Brox approved these changes

2021-12-29 17:07 UTC, D-Brox commented on pacstall/__main__.py
> +        message.fancy("error", "Pacstall cannot be run as root")
This will possibly be implemented in 2.1

2021-12-29 17:07 UTC, merged