Ref/readme
pacstall/pacstall pull request #381
Opened 2021-11-24 09:04 UTC by wizard-28

## Purpose

The badges in the README are outdated.

## Approach

Update those

## Progress

- [x] Change CodeFactor to Codacy badge
- [x] Add `black` code style badge
- [x] Change badge looks and order 

## Addendum

## Checklist

- [ ] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2021-11-24 13:30 UTC, Henryws approved these changes

2021-11-26 12:03 UTC, D-Brox requested changes

2021-11-26 12:03 UTC, D-Brox commented on README.md
> +  <a href="https://github.com/pacstall/pacstall/actions/workflows/remote-bash.yml"><img alt="workflow: status"src="https://github.com/pacstall/pacstall/actions/workflows/remote-bash.yml/badge.svg"></
```suggestion
  <a href="https://github.com/pacstall/pacstall/actions/workflows/remote-bash.yml"><img alt="workflow: status"src="https://img.shields.io/github/workflow/status/pacstall/pacstall/test%20install%20script?label=test%20install&logo=github&style=flat-squareg"></a>
```

2021-11-26 12:08 UTC, D-Brox approved these changes

2021-11-26 12:09 UTC, merged