fix: replace fragile logname/$USER with new variable $user
pacstall/pacstall pull request #405
Opened 2021-12-09 01:59 UTC by Henryws

## Purpose

When logging into some systems, the `logname` command or `$USER` break sometimes

## Approach

Replace all instances of the previous commands with a single variable that tests for `logname` first (most reliable), then tries `$SUDO_USER`, then `$USER` finally.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2021-12-10 09:43 UTC, wizard-28 requested changes

2021-12-10 09:43 UTC, wizard-28 commented on pacstall
> +export user=$(logname 2> /dev/null || echo "${SUDO_USER:-${USER}}")
Shouldn't it be capitalized and something else (so as to not conflict with `USER`), it's a constant after all.

2021-12-10 11:30 UTC, wizard-28 commented
> When logging into some systems, the logname command or $USER break sometimes

This description is embarrassing (due to being *so* vague). File a bug report and link it to this PR.

2021-12-17 17:48 UTC, wizard-28 requested changes
fix the one in the installer, and the uninstaller

2021-12-18 14:03 UTC, wizard-28 requested changes
You missed `upgrade.sh`

2021-12-18 14:21 UTC, Henryws commented
> You missed `upgrade.sh`

Where? I can't find any reference of `$USER` or `logname`

2021-12-18 14:26 UTC, wizard-28 commented
> > You missed `upgrade.sh`
> 
> Where? I can't find any reference of `$USER` or `logname`

`$LOGNAME`

2021-12-18 14:29 UTC, Henryws commented
> You missed `upgrade.sh`

I think you meant `update.sh`

2021-12-18 14:43 UTC, wizard-28 requested changes
You missed `error_log.sh`

2021-12-18 16:09 UTC, wizard-28 approved these changes
Looks good, but didn't test SSH (which is the main reason this change is being done). Hoping @D-Brox would do it.

2021-12-19 15:21 UTC, D-Brox approved these changes
Tested through ssh, worked perfectly

2021-12-19 15:32 UTC, merged