fix(pacstall): outdated version printer for scripting
pacstall/pacstall pull request #426
Opened 2021-12-28 02:13 UTC by Henryws

## Purpose

The version printer `pacstall -V $package` is outdated and was never fixed for newer version of Pacstall leading to weird and breaking output when run.

## Approach

Rework the system

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2021-12-28 08:53 UTC, wizard-28 requested changes
Make a bug report and link it here.

2021-12-28 08:53 UTC, wizard-28 commented on pacstall
>  				# If pacstall -V was called with an argument, it's a package, so get the package version (usful for scripting)
What about this comment?

2021-12-28 08:53 UTC, wizard-28 commented on pacstall
>  					fancy_message error "${GREEN}${PACKAGE}${NC} ins not installed"
What is `ins`

2021-12-28 15:52 UTC, Henryws commented on pacstall
>  					fancy_message error "${GREEN}${PACKAGE}${NC} ins not installed"
Typo, oops

2021-12-29 15:39 UTC, wizard-28 reviewed
What about the completions though? Since this was depreciated we removed the completions for this.

2021-12-29 15:47 UTC, closed without merging