fix(remove.sh): fully remove package
pacstall/pacstall pull request #453
Opened 2022-01-09 15:10 UTC by Henryws

## Purpose

Fully remove package when using the `-R` flag.

## Approach

Purge the package in order to remove metadata and the package completely.

## Addendum

Closes #434 

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2022-01-09 15:18 UTC, wizard-28 requested changes

2022-01-09 15:18 UTC, wizard-28 commented on misc/scripts/remove.sh
> +		if ! sudo --preserve-env=PACSTALL_REMOVE apt purge "$name" 2> /dev/null; then
```suggestion
		if ! sudo --preserve-env=PACSTALL_REMOVE apt-get purge "$name" 2> /dev/null; then
```

2022-01-10 13:15 UTC, wizard-28 approved these changes
Works

2022-01-10 13:50 UTC, D-Brox approved these changes
I suggested this ages ago, for 1.6.1, we should have changed it then...

Anyway, works

2022-01-10 14:04 UTC, merged