fix(install-local): allow apt to downgrade packages
pacstall/pacstall pull request #506
Opened 2022-02-19 00:59 UTC by Henryws

## Purpose

When installing the dummy deb, a git commit id can mess with the versioning, and some commits will be seen as a downgrade to apt.

## Approach

Allow downgrades

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2022-02-19 07:49 UTC, wizard-28 reviewed
Won't this affect pinned dummy debs or something? I forgot what we exactly used.

2022-02-19 14:12 UTC, Henryws commented
> Won't this affect pinned dummy debs or something? I forgot what we exactly used.

![image](https://user-images.githubusercontent.com/58742515/154804414-39474150-2b1a-4809-90ee-08713d770457.png)
It doesn't effect dummy deb pinning

2022-02-19 14:13 UTC, wizard-28 commented
> > Won't this affect pinned dummy debs or something? I forgot what we exactly used.
> 
> ![image](https://user-images.githubusercontent.com/58742515/154804414-39474150-2b1a-4809-90ee-08713d770457.png) It doesn't effect dummy deb pinning

Isn't there a better way to do this?

2022-02-19 14:22 UTC, Henryws commented
Not until the rewrite

2022-02-20 02:55 UTC, wizard-28 requested changes
Write a FAQ, and add a comment in the code.

2022-02-21 14:09 UTC, wizard-28 approved these changes
Okay, but @D-Brox's approval needed

2022-02-24 22:43 UTC, D-Brox approved these changes

2022-02-24 22:48 UTC, merged