fix: allow multiple fields in gives
pacstall/pacstall pull request #526
Opened 2022-03-21 00:10 UTC by Henryws

## Purpose
As it turns out, `gives` (`Provides` in the deb) can have multiple fields.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2022-03-21 06:35 UTC, wizard-28 requested changes
Fix codacy issue, and I'll let @D-Brox handle this.

2022-03-27 13:46 UTC, D-Brox requested changes
Do the same on the `log` function

2022-03-29 21:26 UTC, D-Brox approved these changes

2022-03-29 21:34 UTC, wizard-28 approved these changes

2022-03-29 21:34 UTC, merged