fix: add guards to download and speed up url checking
pacstall/pacstall pull request #535
Opened 2022-03-27 14:11 UTC by Henryws

## Purpose

Currently, in the `develop` branch, the system for determining if a URL was missing, broken, or working is very inefficient, downloading the same file in many different places. 

## Approach

Combine `check_url` and `download`, and make `curl` only check the head of a URL, meaning it won't download the whole file to check the status.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2022-03-27 17:28 UTC, D-Brox requested changes

2022-03-27 17:28 UTC, D-Brox commented on misc/scripts/install-local.sh
> +				error_log 1 "download $PACKAGE"
Add `fancy_message error`.
Same with the others

2022-03-28 23:39 UTC, D-Brox approved these changes

2022-03-29 06:54 UTC, wizard-28 approved these changes

2022-03-29 06:55 UTC, merged