feat(pacstall): spruce up help message
pacstall/pacstall pull request #575
Opened 2022-04-25 22:48 UTC by Henryws

## Purpose

The current help message looks trashy and quickly made (it was).

## Approach

Make it look decent.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2022-04-26 12:18 UTC, wizard-28 requested changes

2022-04-26 12:18 UTC, wizard-28 commented on pacstall
> +
```suggestion
An AUR inspired package manager for Ubuntu.
```

2022-04-26 23:08 UTC, D-Brox approved these changes

2022-04-26 23:18 UTC, volitank approved these changes
Looks good to me. Force push master.

2022-04-28 13:47 UTC, wizard-28 requested changes

2022-04-28 13:47 UTC, wizard-28 commented on pacstall
> +	${BOLD}-U${NC}, ${BOLD}--update${NC}
Shouldn't this have the syntax?

2022-04-28 13:47 UTC, wizard-28 commented on pacstall
> +	An AUR inspired package manager for Ubuntu.
```suggestion
An AUR inspired package manager for Ubuntu.
```

2022-04-28 13:47 UTC, wizard-28 commented on pacstall
> +		Keep the downloaded files.
```suggestion
		Keep the build files.
```

2022-04-28 19:50 UTC, D-Brox commented on pacstall
> +	${BOLD}-U${NC}, ${BOLD}--update${NC}
Oh ye, the optional ones

2022-04-30 18:12 UTC, wizard-28 approved these changes

2022-04-30 18:52 UTC, merged