feat: Parallel package version comparison on upgrade
pacstall/pacstall pull request #632
Opened 2022-08-25 16:32 UTC by D-Brox

## Purpose

The upgrade is too slow, and this gets worse when there is more packages in the repos and packages installed

## Approach

Multi-threading on the version fetch loop, reducing the bottleneck.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2022-08-25 23:36 UTC, Henryws requested changes

2022-08-25 23:36 UTC, Henryws commented on misc/scripts/upgrade.sh
> +N=$(nproc)
```suggestion
N="$(nproc)"
```

2022-08-26 21:16 UTC, Henryws approved these changes

2022-08-30 17:29 UTC, wizard-28 approved these changes

2022-08-30 17:30 UTC, merged