feat: add logging to pacstall functions
pacstall/pacstall pull request #721
Opened 2022-11-28 22:36 UTC by Henryws

## Purpose

Currently we don't have a way of viewing large compilation logs in Pacstall.

## Approach

Redirect stdout and stderr to a log file, and purge month old files.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2022-12-10 18:35 UTC, wizard-28 requested changes

2022-12-10 18:35 UTC, wizard-28 commented on misc/scripts/install-local.sh
> +    local files=("$(find -H "/var/log/pacstall/error_log/" -maxdepth 0 -mtime +30)")
```suggestion
    local files=("$(find -H "/var/log/pacstall/error_log/" -maxdepth 1 -mtime +30)")
```

2022-12-10 18:35 UTC, wizard-28 commented on misc/scripts/install-local.sh
> +    # https://stackoverflow.com/a/29163890 (shorthand for 2>&1 |)
```suggestion
    # NOTE: https://stackoverflow.com/a/29163890 (shorthand for 2>&1 |)
```

2022-12-10 18:41 UTC, wizard-28 approved these changes

2022-12-13 12:43 UTC, D-Brox commented
Fix the pre-commit check failure

2022-12-13 12:49 UTC, Henryws commented
> Fix the pre-commit check failure

The failure is something I already fixed.

2022-12-13 13:18 UTC, D-Brox approved these changes

2022-12-13 13:19 UTC, merged