fix(checks): exit when gives does not exist on deb
pacstall/pacstall pull request #739
Opened 2022-12-17 16:16 UTC by Henryws

## Purpose

`gives` is needed on Debs to get the actual apt package name. If it does not exist, Pacstall will try to remove debs with the apt name `name`, which most definitely is not the canonical name. 

## Approach

Add a check to `check`.

## Addendum

Fixes #736 

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2022-12-17 17:31 UTC, wizard-28 approved these changes

2022-12-21 23:03 UTC, D-Brox approved these changes

2022-12-21 23:04 UTC, D-Brox commented on misc/scripts/install-local.sh
> +            echo "_gives=\"$(dpkg -f ./"${url##*/}" | sed -n "s/^Package: //p")"\"
```suggestion
            echo "_gives=\"$(dpkg -f ./"${url##*/}" | sed -n "s/^Package: //p" |cut -d" " -f2)"\"
```

2022-12-21 23:05 UTC, D-Brox requested changes
~`_gives="Package: name"`~

2022-12-21 23:08 UTC, D-Brox approved these changes

2022-12-21 23:09 UTC, merged