feat(install-local): Run build inside an isolated env
pacstall/pacstall pull request #996
Opened 2023-10-23 18:02 UTC by D-Brox

## Purpose

`pacscripts` can be arbitrary code, and therefore can be unsafe.

This PR reduces the area of attack by running the build functions in an isolated environment by using bwrap. This is done by only giving reat/write permissions inside the `$SRCDIR` source directory and the `$pkgdir` staging directory, while giving read-only to `/`, and no  internet access. After bwrap finishes executing, it will also kill with SIGKILL any child processes that are invoked and outlast it's parent.

## Approach

`run_function()` now uses bwrap.

## Addendum

This is a breaking change, as `sudo` must be removed from every pacscript.

Closes #691

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

2023-10-23 18:06 UTC, Elsie19 requested changes

2023-10-23 18:06 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    return $?
```suggestion
```
Not needed, it's implicit in bash when the last command runs.

2023-10-25 02:20 UTC, Elsie19 requested changes

2023-10-25 02:20 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    echo "#! /bin/bash" | sudo tee "$func.tmp" > /dev/null
```suggestion
    echo "#!/bin/bash" | sudo tee "$func.tmp" > /dev/null
```

It looks better

2023-10-25 02:20 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    echo "#! /bin/bash" | sudo tee "$func.tmp" > /dev/null
We should also randomize the file name, for better security. Maybe with [mktemp](https://linux.die.net/man/1/mktemp)

2023-10-28 14:21 UTC, Elsie19 requested changes

2023-10-28 14:21 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    tmpfile=$(sudo mktemp -p $PWD)
```suggestion
    tmpfile="$(sudo mktemp -p "${PWD}")"
```

2023-10-28 14:21 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +        --ro-bind $envfile $envfile --ro-bind $tmpfile $tmpfile \
```suggestion
        --ro-bind "$envfile" "$envfile" --ro-bind "$tmpfile" "$tmpfile" \
```

2023-10-28 14:21 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    export envfile=$(sudo mktemp -p $SRCDIR)
```suggestion
    export envfile="$(sudo mktemp -p "${SRCDIR}")"
```

2023-10-28 14:21 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    tmpfile=$(sudo mktemp -p $SRCDIR)
```suggestion
    tmpfile="$(sudo mktemp -p "${SRCDIR}")"
```

2023-10-28 14:21 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +        --ro-bind / / --bind $SRCDIR $SRCDIR  --setenv CARCH "$CARCH" --setenv DISTRO "$DISTRO" \
```suggestion
        --ro-bind / / --bind "$SRCDIR" "$SRCDIR" --setenv CARCH "$CARCH" --setenv DISTRO "$DISTRO" \
```

2023-10-28 14:21 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    sudo rm $tmpfile
```suggestion
    sudo rm "$tmpfile"
```

2023-10-28 14:21 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +if ! safe_source || ! source $envfile; then
```suggestion
if ! safe_source || ! source "$envfile"; then
```

2023-10-28 23:43 UTC, Elsie19 requested changes

2023-10-28 23:43 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    sudo rm -f "$safeenv"
```suggestion
    sudo rm -f "$bwrapenv" "$safeenv"
```

2023-10-29 04:18 UTC, Elsie19 requested changes

2023-10-29 04:18 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    tmpfile=$(sudo mktemp -p $PWD)
```suggestion
    tmpfile="$(sudo mktemp -p "${PWD}")"
```

2023-10-29 04:18 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +    sudo rm $tmpfile
```suggestion
    sudo rm "$tmpfile"
```

2023-11-11 19:10 UTC, oklopfer commented
@D-Brox can you fix these?
<img width="1202" alt="Screenshot 2023-11-11 at 2 09 43 PM" src="https://github.com/pacstall/pacstall/assets/104327997/d793b1c8-00e5-49fb-88e5-998fa103c4b6">

2023-11-11 19:13 UTC, D-Brox commented
> @D-Brox can you fix these?
> <img width="1202" alt="Screenshot 2023-11-11 at 2 09 43 PM" src="https://github.com/pacstall/pacstall/assets/104327997/d793b1c8-00e5-49fb-88e5-998fa103c4b6">
> 

The first 2, yes.
The other 2 are probably false positives tho

2023-11-17 01:52 UTC, oklopfer commented
@D-Brox how would this affect packages like [rhino-core](https://github.com/pacstall/pacstall-programs/blob/master/packages/rhino-core/rhino-core.pacscript) and [unicorn-desktop-git](https://github.com/pacstall/pacstall-programs/blob/master/packages/unicorn-desktop-git/unicorn-desktop-git.pacscript) that currently use `post_install` to place files + interact with the unisolated environment (temp packaging directories), like for config files and overwrites?

2023-11-17 01:55 UTC, D-Brox commented
@oklopfer postinst runs inside apt, so no issue

2023-11-17 02:34 UTC, Elsie19 commented
> > @D-Brox can you fix these?
> > <img alt="Screenshot 2023-11-11 at 2 09 43 PM" width="1202" src="https://user-images.githubusercontent.com/104327997/282261065-d793b1c8-00e5-49fb-88e5-998fa103c4b6.png">
> 
> The first 2, yes. The other 2 are probably false positives tho

Can you fix the first two?

2023-11-17 02:38 UTC, oklopfer commented
> @oklopfer `postinst` runs inside `apt`, so no issue

Yay

2023-11-23 17:22 UTC, oklopfer commented
okay I did find a problem with this - certain pacscripts require a second connection to the internet in addition to the `url` variable, but running the builds in the isolated environment makes the second connections inaccessible. 

```bash
[+] INFO: Retrieving packages
Initializing download: https://github.com/hyprwm/xdg-desktop-portal-hyprland/archive/v1.2.5/v1.2.5.tar.gz
File size: unavailable
Opening output file v1.2.5.tar.gz
Server unsupported, starting from scratch with one connection.
Starting download

Connection 0 finished

Downloaded 44.6172 Kilobyte(s) in 0 second(s). (189.48 KB/s)
[+] INFO: Extracting v1.2.5.tar.gz
[+] INFO: Running functions
	[>] Running prepare
	[>] Running build
fatal: unable to access 'https://github.com/hyprwm/hyprland-protocols.git/': Could not resolve host: github.com

ERROR: Neither source directory 'build' nor build directory None contain a build file meson.build.
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory
make: *** hyprland-share-picker: No such file or directory.  Stop.
	[!] ERROR: Could not build xdg-desktop-portal-hyprland properly
dpkg: warning: ignoring request to remove xdg-desktop-portal-hyprland which isn't installed
[+] INFO: Cleaning up
```

2023-11-23 19:16 UTC, D-Brox commented
@oklopfer I can use a flag to share net if needed

2023-11-23 19:40 UTC, oklopfer commented
@D-Brox
![dew-it-galactic-republic](https://github.com/pacstall/pacstall/assets/104327997/9d5c3bc6-9d97-4953-8aed-eb3d1e7b7399)

2023-11-24 21:58 UTC, Elsie19 commented
> @oklopfer I can use a flag to share net if needed

Maybe only for `prepare`, but `build` and `package` are prevented from accessing the internet.

2024-01-21 15:58 UTC, Elsie19 requested changes

2024-01-21 15:58 UTC, Elsie19 commented on misc/scripts/bwrap.sh
> +    echo "echo > \"${safeenv}\"" | sudo tee -a "$tmpfile" > /dev/null
You can wrap all these inside `{}` and have just one `tee` call.

2024-01-21 15:58 UTC, Elsie19 commented on misc/scripts/bwrap.sh
> +    echo "pkgver" | sudo tee -a "$tmpfile" > /dev/null
Wrap in `{}` and use one `tee` call.

2024-01-21 15:58 UTC, Elsie19 commented on misc/scripts/bwrap.sh
> +    echo "source ${bwrapenv}" | sudo tee -a "$tmpfile" > /dev/null
Same as above.

2024-01-21 15:58 UTC, Elsie19 commented on misc/scripts/install-local.sh
> +sudo chown -R "root":"root" . 2> /dev/null
These don't need quoting.

2024-01-21 16:02 UTC, Elsie19 requested changes

2024-01-21 16:02 UTC, Elsie19 commented on misc/scripts/bwrap.sh
> +    echo "#!/bin/bash -ae" | sudo tee "$tmpfile" > /dev/null
I don't like the `-e` flag. Causes *way* too many problems that all pacscripts are checked for either way.

2024-03-31 21:18 UTC, oklopfer commented
this will never work in Docker containers, as they do not allow mounting of /proc in any capacity. `bwrap` must be abandoned in favor of a different wrapper. `fakeroot` or `firejail` may be alternatives.

2024-04-02 03:16 UTC, oklopfer commented
complete in https://github.com/pacstall/pacstall/pull/1068

2024-04-02 03:16 UTC, closed without merging

2024-04-02 03:18 UTC, Elsie19 commented
@D-Brox you have been replaced 😁